name: Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'The tag name of the release where to upload the assets to, for example: v1.2.3'
        required: true
  release:
    types: [created]

jobs:
  build_and_upload_assets:
    name: Build and upload binary assets
    strategy:
      matrix:
        # os: [macos-latest, ubuntu-latest, windows-latest]
        os: [macos-latest, ubuntu-latest]
        include:
          - node-version: 16
          - os: macos-latest
            target: macos
            asset_path: ./bin/vim-doge-macos.tar.gz
          - os: ubuntu-latest
            target: linux
            asset_path: ./bin/vim-doge-linux.tar.gz
          # - os: windows-latest
          #   target: win
          #   asset_path: ./bin/vim-doge-win64.zip
    runs-on : ${{ matrix.os }}
    steps:
      - name: Checkout kkoomen/vim-doge
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup nodejs
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-save --verbose
      - name: Build Unix binary
        if: matrix.target != 'win'
        run: npm run build:binary:unix -- vim-doge-${{ matrix.target }}
      - name: Build Windows binary
        if: matrix.target == 'win'
        run: npm run build:binary:windows -- vim-doge-${{ matrix.target }}64
      - name: Get release
        if: github.event.inputs.tag_name == ''
        id: get_release
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag_name || steps.get_release.outputs.tag_name }}
          files: ${{ matrix.asset_path }}
